#!/bin/bash

[[ "${#}" -ne 1  ]] && { echo "Usage: ${0} gcc-version" 1>&2; exit 1; }

version=${1}
# Assume that if we find gcc, we have the rest
gcc_path=$(which "gcc-${version}")

if [[ $? -eq 0 ]]; then
  export CC="/usr/local/bin/gcc-${version}"
  export CXX="/usr/local/bin/g++-${version}"
  export CPP="/usr/local/bin/cpp-${version}"
  export LD="/usr/local/bin/gcc-${version}"
  export CFLAGS=-Wno-error=deprecated-declarations
else
  echo "GCC version ${version} not found. Exiting" 1>&2; exit 1;
fi

